import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(await fs.realpath(new URL('../node_modules/wrangler/package.json',import.meta.url)));
const {Miniflare}=require('miniflare');
const root=new URL('..',import.meta.url).pathname;
const moduleFiles=(await fs.readdir(root+'dist/server',{recursive:true})).filter(p=>/\.m?js$/.test(p)); const modules=[{type:'ESModule',path:root+'dist/server/index.js'},...moduleFiles.filter(p=>p!=='index.js').map(p=>({type:'ESModule',path:root+'dist/server/'+p}))];
const mf=new Miniflare({modules,modulesRoot:root+'dist/server',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{CONNECTOR_SECRET:'test-only-connector-secret-not-production'}});
const results=[];let cookie='';
const db=await mf.getD1Database('DB');
const sql=await fs.readFile(root+'drizzle/0000_flat_the_leader.sql','utf8');
for(const statement of sql.split('--> statement-breakpoint'))if(statement.trim())await db.prepare(statement).run();
async function call(path,body,extra={}){let payload=body,formHeaders={};if(body instanceof FormData){const encoded=new Request('https://test.local',{method:'POST',body});formHeaders={'Content-Type':encoded.headers.get('content-type')};payload=await encoded.arrayBuffer();}const res=await mf.dispatchFetch('https://test.local/api/'+path,{method:body===undefined?'GET':'POST',headers:{...(cookie?{cookie}:{}),...(body instanceof FormData?{}:body!==undefined?{'Content-Type':'application/json'}:{}),...formHeaders,...extra},body:body instanceof FormData?payload:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];const content=res.headers.get('content-type')?.includes('application/json')?await res.json():await res.text();return {status:res.status,data:content};}
async function ok(path,body,headers={}){const r=await call(path,body,headers);assert(r.status<300,`${path}: ${r.status} ${JSON.stringify(r.data)}`);return r.data;}
async function job(name='Acceptance test'){return ok('jobs',{customer:name,quantity:500,sides:2,stock:'14pt matte',finish:'Matte',due:'2026-10-10'});}
async function upload(j,name){const f=new FormData();f.set('file',new File([await fs.readFile(root+'tests/fixtures/'+name+'.pdf')],name+'.pdf',{type:'application/pdf'}));return ok(`jobs/${j.id}/artwork`,f);}
async function process(j){await ok(`jobs/${j.id}/process`,{generation:j.generation});for(let k=0;k<100;k++){await new Promise(r=>setTimeout(r,100));const current=await ok('jobs/'+j.id);if(!current.tasks.some(t=>t.status==='Running')&&current.tasks[2].status!=='Pending')return current;}throw new Error('Timed out');}
async function action(j,action,extra={}){return ok(`jobs/${j.id}/action`,{generation:j.generation,action,...extra});}
function pass(id,detail){results.push({id,status:'PASS',evidence:detail});console.log('PASS',id,detail);}
try{
 assert.equal((await call('jobs')).status,401);pass('authentication','Anonymous job access denied.');
 await ok('auth/setup',{email:'qa@print2go.test',name:'QA operator',password:'Qa-fixture-only-strong-password'});
 let j=await job();pass(1,`Created ${j.id} through API without chat.`);
 j=await upload(j,'valid');j=await process(j);assert.equal(j.tasks[6].status,'Completed',JSON.stringify({tasks:j.tasks.slice(2,7),inspection:j.inspection}));assert.equal(j.tasks[7].status,'Waiting for approval');let f=j.files.findLast(f=>f.stage==='PRINT_READY');assert(f&&f.bytes>0);assert.equal(j.verification.sha,f.sha);pass(2,`PDF ${f.id}, SHA ${f.sha}, ${f.bytes} bytes. Reopened verification passed.`);
 const produced=await mf.dispatchFetch(`https://test.local/api/files/${j.id}/${f.id}`,{headers:{cookie}});await fs.mkdir(root+'tests/results',{recursive:true});await fs.writeFile(root+'tests/results/PRINT_READY.pdf',Buffer.from(await produced.arrayBuffer()));
 pass(6,'Authenticated proof file endpoint returns the actual two-page generated PDF. Canvas rendering requires browser verification.');
 j=await action(j,'approve',{sha:f.sha,acknowledged:true});assert.equal(j.approval.sha,f.sha);pass(7,`Approval records file ${f.id}, generation ${j.generation}, QA operator and timestamp.`);
 const firstApprovalAt=j.approval.at;const again=await call(`jobs/${j.id}/action`,{generation:j.generation,action:'approve',sha:f.sha,acknowledged:true});assert(again.status<300); // repeated approval should return existing evidence
 assert.equal(again.data.approval.at,firstApprovalAt,'Repeated approval must not overwrite evidence');
 let missing=await upload(await job('Missing bleed'),'trim');missing=await process(missing);assert.equal(missing.tasks[3].status,'Needs attention');assert(!missing.files.some(f=>f.stage==='PRINT_READY'));missing=await action(missing,'bleed',{decision:'blank-border'});missing=await process(missing);assert.equal(missing.tasks[6].status,'Completed',JSON.stringify({tasks:missing.tasks.slice(2,7),verification:missing.verification}));pass(3,'Trim-only file stopped for explicit blank-border decision; no output generated before decision.');
 let wrong=await upload(await job('Wrong size'),'wrong');wrong=await process(wrong);assert.equal(wrong.tasks[2].status,'Blocked');assert(!wrong.files.some(f=>f.stage==='PRINT_READY'));let edge=await upload(await job('Unsafe text'),'edge');edge=await process(edge);assert.equal(edge.tasks[2].status,'Blocked');pass(4,'Incorrect size and unsafe detectable text blocked production; revised-upload recovery recorded.');
 let low=await upload(await job('Measured low dpi'),'low-dpi');low=await process(low);assert(low.inspection.warnings.some(w=>/36 dpi/.test(w)),JSON.stringify(low.inspection));pass(5,JSON.stringify(low.inspection.pages[0].images));
 j=await upload(j,'valid');assert(!j.approval&&!j.authorization);assert.equal(j.tasks[6].status,'Pending');pass(8,'Artwork replacement incremented generation, revoked approval and authorization, reset downstream checks.');
 const refreshed=await ok('jobs/'+j.id);assert.equal(refreshed.generation,j.generation);assert.equal(refreshed.files.length,j.files.length);pass(9,'New GET preserved job state, lineage and generation from D1/R2.');
 const chatFail=await call(`jobs/${j.id}/chat`,{message:'Inspect the file'});assert.equal(chatFail.status,503);let broken=await job('Corrupt PDF');const data=new FormData();data.set('file',new File(['%PDF-broken-content'],'broken.pdf'));broken=await ok(`jobs/${broken.id}/artwork`,data);broken=await process(broken);assert.equal(broken.tasks[2].status,'Failed');assert(broken.tasks[2].recovery);pass(10,'Claude without credentials returned an honest 503; corrupt PDF produced Failed with recovery details.');
 j=await process(j);f=j.files.findLast(f=>f.stage==='PRINT_READY');j=await action(j,'approve',{sha:f.sha,acknowledged:true});await ok('settings',{printer:'QA operator-assisted printer',stocks:['14pt matte'],sides:[1,2],instructions:'Stage only; never print automatically.',model:'claude-sonnet-4-5'});j=await action(j,'route');j=await action(j,'handoff',{note:'QA staging confirmation; no physical printing performed.'});j=await action(j,'readiness');assert.equal(j.tasks[10].status,'Blocked');pass(11,'Disconnected connector blocked readiness and production authorization.');
 const early=await call(`jobs/${j.id}/action`,{action:'printed',generation:j.generation,sha:f.sha,acknowledged:true});assert(early.status>=400);pass(13,'Print confirmation rejected before readiness and explicit authorization.');
 const header={Authorization:'Bearer test-only-connector-secret-not-production'};
 await ok('connector',{timestamp:Date.now(),nonce:crypto.randomUUID(),destination:'QA-only staging fixture (not shop hardware)',writable:true,capabilities:['pdf-hot-folder'],handoffs:[]},header);
 j=await action(j,'readiness');assert.equal(j.tasks[10].status,'Completed');j=await action(j,'authorize',{sha:f.sha,acknowledged:true});assert.equal(j.tasks[12].status,'Waiting for operator');
 const authorizedFile=await mf.dispatchFetch('https://test.local/api/connector/file/'+j.id,{headers:header});assert.equal(authorizedFile.status,200);const sha=(await import('node:crypto')).createHash('sha256').update(Buffer.from(await authorizedFile.arrayBuffer())).digest('hex');assert.equal(sha,f.sha);
 await ok('connector',{timestamp:Date.now(),nonce:crypto.randomUUID(),destination:'QA-only staging fixture (not shop hardware)',writable:true,capabilities:['pdf-hot-folder'],handoffs:[{jobId:j.id,sha:f.sha,generation:j.generation,fileId:f.id}]},header);
 j=await ok('jobs/'+j.id);assert.equal(j.files.filter(f=>f.stage==='PRODUCTION_OUTPUT').length,1);assert.equal(j.files.findLast(f=>f.stage==='PRODUCTION_OUTPUT').sha,f.sha);const fakeCopy=await ok('jobs/'+j.id);assert.notEqual(fakeCopy.tasks[12].status,'Completed');pass('connector-handoff','Authorized PDF checksum matched; handoff acknowledgment created one PRODUCTION_OUTPUT record without marking physical printing complete.');
 j=await action(j,'printed',{sha:f.sha,acknowledged:true});j=await action(j,'cut',{sha:f.sha,acknowledged:true});
 j=await action(j,'qc',{sha:f.sha,acknowledged:true,checks:{quantity:true,alignment:false,appearance:true,finishing:true,note:'QA test rejection'}});assert.equal(j.tasks[14].status,'Needs attention');assert(!j.authorization);j=await action(j,'rework');assert.equal(j.tasks[11].status,'Waiting for approval');
 j=await action(j,'authorize',{sha:f.sha,acknowledged:true});j=await action(j,'printed',{sha:f.sha,acknowledged:true});j=await action(j,'cut',{sha:f.sha,acknowledged:true});j=await action(j,'qc',{sha:f.sha,acknowledged:true,checks:{quantity:true,alignment:true,appearance:true,finishing:true,note:'QA only'}});j=await action(j,'pack',{sha:f.sha,acknowledged:true,method:'collection'});assert.equal(j.state,'complete');pass(14,'Operator confirmation required for print, cut, QC and pack; rejected QC revoked authorization, rework required authorization again. API fixtures only; no hardware printed.');
 let double=await upload(await job('Concurrent requests'),'valid');const twice=await Promise.all([call(`jobs/${double.id}/process`,{generation:double.generation}),call(`jobs/${double.id}/process`,{generation:double.generation})]);assert(twice.filter(r=>r.status<300&&r.data.queued).length===1,JSON.stringify(twice));for(let k=0;k<100;k++){double=await ok('jobs/'+double.id);if(double.tasks[6].status==='Completed')break;await new Promise(r=>setTimeout(r,100));}assert.equal(double.files.filter(f=>f.stage==='PRINT_READY').length,1);const retry=await ok(`jobs/${double.id}/process`,{generation:double.generation});assert.equal(retry.queued,false);pass(12,'Concurrent clicks: one lease, one output. Repeated processing and proof approval retain existing evidence.');
 await ok(`jobs/${double.id}/control`,{state:'paused'});assert.equal((await ok('jobs/'+double.id)).state,'paused');assert.equal((await call(`jobs/${double.id}/action`,{action:'approve',generation:double.generation,sha:double.files.findLast(f=>f.stage==='PRINT_READY').sha,acknowledged:true})).status,409);await ok(`jobs/${double.id}/control`,{state:'active'});pass('pause-resume','Paused job rejects actions; resume restores active state.');
 double=await ok('jobs/'+double.id);const df=double.files.findLast(f=>f.stage==='PRINT_READY');double=await action(double,'approve',{sha:df.sha,acknowledged:true});double=await action(double,'route');double=await action(double,'handoff',{note:'QA route invalidation fixture'});double=await action(double,'readiness');double=await action(double,'authorize',{sha:df.sha,acknowledged:true});await ok('settings',{printer:'Changed QA route',stocks:['14pt matte'],sides:[1,2],instructions:'Changed staging settings',model:'claude-sonnet-4-5'});double=await ok('jobs/'+double.id);assert.equal(double.tasks[8].status,'Pending');assert(!double.authorization);assert.equal(double.approval.sha,df.sha);pass('settings-invalidation','Changing production settings reset route/readiness and revoked authorization, preserving the unchanged file proof.');
 let interrupted=await upload(await job('Interrupted processing'),'valid');interrupted.tasks[2].status='Running';await db.prepare('UPDATE records SET data=?,lock=?,locked_at=? WHERE id=?').bind(JSON.stringify(interrupted),'interrupted-test-lease',Date.now()-130000,interrupted.id).run();interrupted=await ok('jobs/'+interrupted.id);assert.equal(interrupted.tasks[2].status,'Failed');interrupted=await process(interrupted);assert.equal(interrupted.tasks[6].status,'Completed');pass('interruption-recovery','Expired processing lease became a recoverable Failed task; retry resumed from saved state and produced a verified PDF.');
 await ok('users',{email:'operator@print2go.test',name:'Restricted operator',password:'Operator-fixture-only-password',role:'operator'});await ok('auth/logout',{});await ok('auth/login',{email:'operator@print2go.test',password:'Operator-fixture-only-password'});assert.equal((await call('settings',{printer:'Attempted override',stocks:['x'],sides:[1],instructions:'',model:''})).status,409);pass('operator-permissions','Operator can sign in but cannot change admin configuration.');
 const s=await ok('settings');assert(!JSON.stringify(s).includes('test-only-connector-secret-not-production'));pass(16,'Settings responses contain configuration flags only; no Anthropic key or connector secret. Server-only credential code is excluded from client imports.');
 results.push({id:15,status:'NOT VERIFIED',evidence:'Responsive light/dark layouts implemented at desktop, tablet and mobile breakpoints. Browser-control skill unavailable; visual browser QA not claimed.'});
 results.push({id:'Claude live',status:'NOT VERIFIED',evidence:'No real Anthropic credentials supplied. Missing-key path was verified.'});
 results.push({id:'Shop live',status:'NOT VERIFIED',evidence:'Local heartbeat protocol tested using isolated QA fixtures. No shop hardware or machine access available.'});
}catch(e){results.push({status:'FAIL',evidence:e.message});console.error(e);}
finally{await fs.mkdir(root+'tests/results',{recursive:true});await fs.writeFile(root+'tests/results/acceptance.json',JSON.stringify(results,null,2));await mf.dispose();}
if(results.some(r=>r.status==='FAIL'))globalThis.process.exitCode=1;
