// Protocol fixture tests. These are not live-provider or production-success claims.
import assert from 'node:assert/strict';
import {providerOrder,streamTurn,firstTurn,openAIInput} from '../lib/production/providers.ts';
const calls=[],text=[];const tools=[{name:'get_job',description:'Read verified data',input_schema:{type:'object',properties:{},additionalProperties:false}}];
function stream(events){const data=events.map(e=>'data: '+JSON.stringify(e)+'\r\n\r\n').join('');return new Response(data,{headers:{'Content-Type':'text/event-stream'}});}
const configs=providerOrder({ANTHROPIC_API_KEY:'fixture-anthropic-secret',OPENAI_API_KEY:'fixture-openai-secret'});assert.deepEqual(configs.map(c=>c.provider),['claude','openai']);assert.equal(providerOrder({OPENAI_API_KEY:'fixture'}).length,1);assert.equal(providerOrder({AI_PRIMARY_PROVIDER:'claude',OPENAI_API_KEY:'fixture',AI_FALLBACK_ENABLED:'false'}).length,0);
const result=await firstTurn(configs,'No hidden reasoning',[{role:'user',content:'Read this job'}],tools,t=>text.push(t),async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});if(url.includes('anthropic'))return new Response('{}',{status:503});return stream([{type:'response.output_text.delta',delta:'Reading saved results.'},{type:'response.reasoning_text.delta',delta:'PRIVATE THINKING MUST NOT BE EXPOSED'},{type:'response.completed',response:{output:[{type:'function_call',call_id:'call_fixture',name:'get_job',arguments:'{}'}]}}]);});
assert.equal(result.config.provider,'openai');assert.equal(calls.length,2);assert.deepEqual(text,['Reading saved results.']);assert.equal(result.content[1].name,'get_job');assert.equal(calls[1].body.store,false);assert.equal(calls[1].body.parallel_tool_calls,false);assert.equal(calls[1].body.tools[0].strict,true);assert(!JSON.stringify(result.content).includes('PRIVATE THINKING'));
const input=openAIInput([{role:'assistant',content:result.content},{role:'user',content:[{type:'tool_result',tool_use_id:'call_fixture',content:'{"status":"Blocked"}'}]}]);assert.equal(input.find(i=>i.type==='function_call_output').call_id,'call_fixture');assert(!JSON.stringify(input).includes('fixture-openai-secret'));
let requests=0;await assert.rejects(()=>firstTurn(configs,'system',[{role:'user',content:'help'}],tools,()=>{},async()=>{requests++;return stream([{type:'content_block_start',index:0,content_block:{type:'text',text:''}},{type:'content_block_delta',index:0,delta:{type:'text_delta',text:'Partial'}},{type:'error',error:{message:'fixture'}}]);}));assert.equal(requests,1,'Do not fallback after visible output');
const claude=await streamTurn(configs[0],'system',[{role:'user',content:'get job'}],tools,()=>{},async()=>stream([{type:'content_block_start',index:0,content_block:{type:'tool_use',id:'tool_fixture',name:'get_job',input:{}}},{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'{}'}},{type:'message_stop'}]));assert.deepEqual(claude,[{type:'tool_use',id:'tool_fixture',name:'get_job',input:{}}]);
await assert.rejects(()=>streamTurn(configs[1],'system',[],tools,()=>{},async()=>stream([{type:'response.output_text.delta',delta:'Incomplete'}])));
console.log('PASS: provider routing, strict tool format, both SSE adapters, safe fallback, shared tool-result identity, no hidden-reasoning display, truncated-stream rejection. Protocol fixtures only; live credentials not configured.');
