import { read,save,db,now,runtime,hash,lock,unlock } from './store';
import { product } from './products';
import type { Job,Status,FileRecord } from './types';
export function event(j:Job,text:string,actor='Application'){j.events.push({id:crypto.randomUUID(),text,actor,at:now()});}
export function task(j:Job,index:number,status:Status,result:string,execution?:string,evidence?:string){const t=j.tasks[index];t.status=status;t.result=result;t.updated=now();if(status==='Running')t.started=now();if(status==='Completed'){t.started||=now();t.finished=now();}if(execution&&!t.executions.includes(execution))t.executions.push(execution);if(evidence&&!t.evidence.includes(evidence))t.evidence.push(evidence);t.next=status==='Failed'||status==='Needs attention'?'Review details and retry, or upload revised artwork.':status==='Waiting for approval'?'Review the proof and approve this file version.':status==='Waiting for operator'?'Confirm the physical step when it is finished.':'';event(j,result);}
export function latest(j:Job,stage:FileRecord['stage']){return [...j.files].reverse().find(x=>x.stage===stage);}
export async function bytes(f:FileRecord){const o=await runtime().BUCKET.get(f.key);if(!o)throw new Error('The saved file is unavailable. Retry or upload the original again.');const b=new Uint8Array(await o.arrayBuffer());if(await hash(b)!==f.sha)throw new Error('Saved file identity does not match its recorded checksum.');return b;}
export async function file(j:Job,stage:FileRecord['stage'],b:Uint8Array,parent:FileRecord|undefined,method:string,name?:string){const id=crypto.randomUUID(),key=`jobs/${j.id}/${id}.pdf`;const f:FileRecord={id,key,stage,name:name||`${j.id}-${stage}.pdf`,bytes:b.length,sha:await hash(b),created:now(),parent:parent?.id,method};await runtime().BUCKET.put(key,b,{httpMetadata:{contentType:'application/pdf'}});j.files.push(f);return f;}
export function requireBefore(j:Job,i:number){if(j.state!=='active')throw new Error(`This job is ${j.state}. Resume it before continuing.`);for(let n=0;n<i;n++)if(j.tasks[n].status!=='Completed')throw new Error(`Finish “${j.tasks[n].title}” first.`);}
export function invalidate(j:Job,from:number,reason:string){j.generation++;for(let i=from;i<16;i++){const t=j.tasks[i];t.status='Pending';t.result=reason;t.next='';t.error=undefined;t.recovery=undefined;t.finished=undefined;t.executions=[];t.evidence=[];}if(from<=7)j.approval=undefined;j.authorization=undefined;if(from<=8)j.route=undefined;if(from<=6)j.verification=undefined;if(from<=3)j.bleedDecision=undefined;event(j,reason);}
async function control(j:Job,token:string){const c=await read(`control:${j.id}`);if(c?.state==='paused'||c?.state==='cancelled'){j.state=c.state;if(j.state==='cancelled')for(const t of j.tasks)if(t.status!=='Completed')t.status='Cancelled';await save(j,token);return false;}return true;}
export async function process(j:Job,token:string,execution:string){
 let index=2;const {inspect,prepare,verify}=product(j.recipe.id);
 try{
 for(index=2;index<=6;index++){
  if(!await control(j,token))return;
  if(j.tasks[index].status==='Completed')continue;
  requireBefore(j,index);task(j,index,'Running',`Working on ${j.tasks[index].title.toLowerCase()}.`,execution);await save(j,token);
  const original=latest(j,'ORIGINAL');if(!original)throw new Error('Upload artwork first.');
  if(index===2){j.inspection=await inspect(await bytes(original),j.recipe,j.sides);if(j.inspection.errors.length){task(j,index,'Blocked',j.inspection.errors.join(' '),execution,original.id);j.tasks[index].recovery='Upload a revised PDF. No production file was approved.';await save(j,token);return;}task(j,index,'Completed',`Checked ${j.sides} page(s). ${j.inspection.warnings.length} review note(s).`,execution,original.id);}
  if(index===3){if(j.inspection?.bleed==='missing'&&!j.bleedDecision){task(j,index,'Needs attention','Artwork is trim size only. Choose corrected artwork or explicitly accept a blank border outside trim.',execution,original.id);await save(j,token);return;}task(j,index,'Completed',j.bleedDecision==='blank-border'?'Operator accepted a blank border outside trim. Design content stays at its original size.':'Bleed dimensions match. Edge coverage still requires visual proof review.',execution,original.id);}
  if(index===4){const b=await prepare(await bytes(original),j.recipe,j.bleedDecision==='blank-border');const f=await file(j,'WORKING_COPY',b,original,'Preserve content; set recipe page boxes'+(j.bleedDecision==='blank-border'?'; add operator-approved blank border':''));task(j,index,'Completed','Working copy saved. Original artwork preserved.',execution,f.id);}
  if(index===5){const working=latest(j,'WORKING_COPY');if(!working)throw new Error('Working copy is missing.');const f=await file(j,'PRINT_READY',await bytes(working),working,'Production PDF from prepared working copy; no colour or font substitution');task(j,index,'Completed','Production PDF generated and stored with a checksum.',execution,f.id);}
  if(index===6){const f=latest(j,'PRINT_READY');if(!f)throw new Error('Production PDF is missing.');const report=await verify(await bytes(f),j.recipe,j.sides);j.verification={...report,fileId:f.id,sha:f.sha,recipeVersion:j.recipe.version,generation:j.generation};if(report.errors.length){task(j,index,'Blocked',report.errors.join(' '),execution,f.id);await save(j,token);return;}task(j,index,'Completed','Stored production PDF reopened and independently checked against the pinned recipe.',execution,f.id);task(j,7,'Waiting for approval','Your actual production proof is ready. Review every page and all inspection notes.',execution,f.id);}
  await save(j,token);
 }
 }catch(e){const t=j.tasks[Math.min(index,6)];t.error=e instanceof Error?e.message:'PDF processing failed.';t.recovery='Retry this step. If it fails again, export a fresh PDF and upload it.';task(j,Math.min(index,6),'Failed',t.error,execution);await save(j,token);}
}
export async function queue(jobId:string,user:any){const token=await lock(jobId);const j=await read<Job>(jobId);if(!j){await unlock(jobId,token);throw new Error('Job not found.');}try{requireBefore(j,2);if(j.tasks[6].status==='Completed'){await unlock(jobId,token);return {queued:false};}const id=crypto.randomUUID();await db().prepare('INSERT INTO executions (id,job_id,action,status,data,created) VALUES (?,?,?,?,?,?)').bind(id,j.id,'process','Running',JSON.stringify({actor:user.name,generation:j.generation}),now()).run();return {id,run:async()=>{try{await process(j,token,id);await db().prepare('UPDATE executions SET status=?,data=? WHERE id=?').bind(j.tasks.some(t=>t.status==='Failed'||t.status==='Blocked')?'Failed':'Completed',JSON.stringify({actor:user.name,generation:j.generation,finished:now(),events:j.events.slice(-12)}),id).run();}finally{await unlock(j.id,token);}}};}catch(e){await unlock(jobId,token);throw e;}}
export async function recover(j:Job){const r=await db().prepare('SELECT lock,locked_at FROM records WHERE id=?').bind(j.id).first<any>();if(r?.lock&&r.locked_at<Date.now()-120000){const token=await lock(j.id);try{j=await read<Job>(j.id) as Job;for(const t of j.tasks)if(t.status==='Running'){t.status='Failed';t.result='Execution was interrupted. Retry safely from the last saved step.';t.error='Execution lease expired';t.recovery='Choose Retry checks.';}event(j,'Recovered an interrupted execution. Completed evidence was retained.');await db().prepare('UPDATE executions SET status=? WHERE job_id=? AND status=?').bind('Interrupted',j.id,'Running').run();await save(j,token);}finally{await unlock(j.id,token);}}return j;}
export async function readiness(j:Job){const settings=await read('settings'),agent=await read('agent');if(!settings?.printer)throw new Error('Configure a printer in Shop settings.');if(!j.route||j.route.settingsVersion!==settings.version)throw new Error('Production settings changed. Choose the route again.');if(!agent?.lastSeen||Date.now()-Date.parse(agent.lastSeen)>90000||!agent.writable||!agent.capabilities?.includes('pdf-hot-folder'))throw new Error('Shop disconnected. Start the local connector and confirm the destination is writable.');return {lastSeen:agent.lastSeen,destination:agent.destination,capabilities:agent.capabilities,printer:settings.printer,checkedAt:now()};}
