import { PDFDocument, PDFName, PDFArray, PDFRawStream, decodePDFRawStream } from 'pdf-lib';
import type { Recipe, Inspection } from './types';
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import { WorkerMessageHandler } from 'pdfjs-dist/legacy/build/pdf.worker.mjs';
(globalThis as any).pdfjsWorker={WorkerMessageHandler};
const close=(a:number,b:number)=>Math.abs(a-b)<0.75;
const multiply=(a:number[],b:number[])=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
export async function inspect(bytes:Uint8Array,r:Recipe,sides:number):Promise<Inspection>{
 const doc=await PDFDocument.load(bytes,{updateMetadata:false});const errors:string[]=[],warnings:string[]=[],pages:any[]=[];
 if(doc.getPageCount()!==sides)errors.push(`Expected ${sides} page(s), found ${doc.getPageCount()}. Upload one PDF with the front, then the back.`);
 if(doc.getPageCount()>2)throw new Error('Business cards support at most two PDF pages.');
 if(doc.getForm().getFields().length)errors.push('Interactive form fields must be flattened by the artwork designer before upload.');
 const loadingTask=pdfjs.getDocument({data:bytes.slice(),useSystemFonts:false,isEvalSupported:false,disableFontFace:true,stopAtErrors:true} as any);const parsed=await loadingTask.promise;
 let bleed:'correct'|'missing'|'unsuitable'='correct';
 try {for(let n=0;n<doc.getPageCount();n++){
  const page=doc.getPage(n),size=page.getSize(),full=close(size.width,(r.width+2*r.bleed)*72)&&close(size.height,(r.height+2*r.bleed)*72),trim=close(size.width,r.width*72)&&close(size.height,r.height*72);
  if(!full&&!trim){errors.push(`Page ${n+1}: ${ (size.width/72).toFixed(3)} × ${(size.height/72).toFixed(3)} inches does not match the recipe. No stretching is allowed.`);bleed='unsuitable';}else if(trim&&bleed!=='unsuitable')bleed='missing';
  if(page.getRotation().angle!==0)errors.push(`Page ${n+1}: rotated page. Export an unrotated PDF.`);
  const annotations=page.node.lookupMaybe(PDFName.of('Annots'),PDFArray);if(annotations&&annotations.size()>0)errors.push(`Page ${n+1}: annotations detected. Flatten comments, links and annotations before upload.`);
  const pj=await parsed.getPage(n+1),text=await pj.getTextContent(),ops=await pj.getOperatorList();
  const edgeTexts:any[]=[];const offset=full?r.bleed*72:0,safe=r.safe*72;
  for(const item of text.items as any[]){if(!item.str?.trim())continue;const t=item.transform;const h=Math.hypot(t[2],t[3])||item.height;const x=t[4],y=t[5];if(Math.abs(t[1])>.01||Math.abs(t[2])>.01){warnings.push(`Page ${n+1}: angled text needs visual safe-area review.`);continue;}const box=[x,y-h*.25,x+item.width,y+h*.85];if(box[0]<offset+safe||box[1]<offset+safe||box[2]>size.width-offset-safe||box[3]>size.height-offset-safe){edgeTexts.push({bounds:box.map(v=>Number(v.toFixed(2)))});}}
  if(edgeTexts.length)errors.push(`Page ${n+1}: ${edgeTexts.length} text span(s) detected inside the protected safe margin. Move essential text inward and upload a revised PDF.`);
  const contents=page.node.Contents();const streams=contents instanceof PDFArray?contents.asArray().map(ref=>doc.context.lookup(ref)):[contents];let content='';for(const stream of streams){if(stream instanceof PDFRawStream)content+=new TextDecoder('latin1').decode(decodePDFRawStream(stream).decode());}const usedFonts=new Set<string>();let activeFont='';for(const match of content.matchAll(/\/([A-Za-z0-9+_.-]+)\s+[-+\d.]+\s+Tf|\b(Tj|TJ)\b/g)){if(match[1])activeFont=match[1];else if(activeFont)usedFonts.add('/'+activeFont);}const resources=page.node.Resources(),fonts:any[]=[];const fontDict=resources?.lookupMaybe(PDFName.of('Font'),(await import('pdf-lib')).PDFDict);
  if(fontDict)for(const [name,ref] of fontDict.entries()){const f=doc.context.lookup(ref) as any;let descriptor=f?.lookup?.(PDFName.of('FontDescriptor'));const descendants=f?.lookup?.(PDFName.of('DescendantFonts'));if(!descriptor&&descendants?.size?.())descriptor=descendants.lookup(0)?.lookup?.(PDFName.of('FontDescriptor'));const embedded=!!(descriptor?.get?.(PDFName.of('FontFile'))||descriptor?.get?.(PDFName.of('FontFile2'))||descriptor?.get?.(PDFName.of('FontFile3')));fonts.push({name:name.toString(),embedded,used:usedFonts.has(name.toString())});if(!embedded&&usedFonts.has(name.toString()))errors.push(`Page ${n+1}: ${name.toString()} is not embedded. Embed fonts or outline text before uploading.`);}
  let matrix=[1,0,0,1,0,0];const stack:number[][]=[],images:any[]=[];const colors=new Set<string>();
  for(let i=0;i<ops.fnArray.length;i++){const op=ops.fnArray[i],args=ops.argsArray[i];if(op===pdfjs.OPS.save)stack.push([...matrix]);if(op===pdfjs.OPS.restore)matrix=stack.pop()||[1,0,0,1,0,0];if(op===pdfjs.OPS.transform)matrix=multiply(matrix,args);if(op===pdfjs.OPS.paintImageXObject||op===pdfjs.OPS.paintInlineImageXObject){const w=op===pdfjs.OPS.paintImageXObject?args[1]:args[0]?.width,h=op===pdfjs.OPS.paintImageXObject?args[2]:args[0]?.height;const sx=Math.hypot(matrix[0],matrix[1])/72,sy=Math.hypot(matrix[2],matrix[3])/72;if(w&&h&&sx&&sy){const dpi=Math.min(w/sx,h/sy);images.push({pixels:[w,h],placedInches:[sx,sy],dpi:Number(dpi.toFixed(1))});if(dpi<r.minDpi)warnings.push(`Page ${n+1}: an image measures ${dpi.toFixed(0)} dpi at its placed size; target is ${r.minDpi} dpi.`);}}if(op===pdfjs.OPS.setFillRGBColor||op===pdfjs.OPS.setStrokeRGBColor)colors.add('RGB');if(op===pdfjs.OPS.setFillCMYKColor||op===pdfjs.OPS.setStrokeCMYKColor)colors.add('CMYK');if(op===pdfjs.OPS.setFillGray||op===pdfjs.OPS.setStrokeGray)colors.add('Gray');}
  pages.push({page:n+1,widthInches:size.width/72,heightInches:size.height/72,mediaBox:page.getMediaBox(),trimBox:page.getTrimBox(),bleedBox:page.getBleedBox(),cropBox:page.getCropBox(),fonts,images,nearTrim:edgeTexts,colourOperators:[...colors]});
 }
 }finally{await loadingTask.destroy();}
 warnings.push('Font-embedding checks cover detected text fonts in top-level content. Nested forms and unusual text operators need expert review. Image measurements cover direct image placements. Nested forms, masks, vector logos and transparency need visual review. Colour operators do not certify output colour; no colour conversion is applied. Text bounds are approximate; inspect every proof for clipping and essential graphics near trim.');
 if(bleed==='correct')warnings.push('Page size includes bleed. This cannot prove the design extends to every bleed edge; confirm visually.');
 return {pages,errors:[...new Set(errors)],warnings:[...new Set(warnings)],bleed,engine:'PDF.js parser + pdf-lib structure inspection',at:new Date().toISOString()};
}
export async function prepare(bytes:Uint8Array,r:Recipe,blankBorder:boolean){const doc=await PDFDocument.load(bytes,{updateMetadata:false});for(const page of doc.getPages()){if(blankBorder&&close(page.getWidth(),r.width*72)&&close(page.getHeight(),r.height*72)){page.setSize((r.width+2*r.bleed)*72,(r.height+2*r.bleed)*72);page.translateContent(r.bleed*72,r.bleed*72);}page.setMediaBox(0,0,(r.width+2*r.bleed)*72,(r.height+2*r.bleed)*72);page.setCropBox(0,0,(r.width+2*r.bleed)*72,(r.height+2*r.bleed)*72);page.setBleedBox(0,0,(r.width+2*r.bleed)*72,(r.height+2*r.bleed)*72);page.setTrimBox(r.bleed*72,r.bleed*72,r.width*72,r.height*72);}return doc.save({useObjectStreams:false});}
export async function verify(bytes:Uint8Array,r:Recipe,sides:number){const report=await inspect(bytes,r,sides);const doc=await PDFDocument.load(bytes,{updateMetadata:false});for(const p of doc.getPages()){const t=p.getTrimBox(),b=p.getBleedBox();if(!close(t.x,r.bleed*72)||!close(t.y,r.bleed*72)||!close(t.width,r.width*72)||!close(t.height,r.height*72)||!close(b.width,(r.width+2*r.bleed)*72)||!close(b.height,(r.height+2*r.bleed)*72))report.errors.push('Generated page boxes do not match the pinned recipe.');}return report;}
