export type Status = 'Pending'|'Running'|'Needs attention'|'Waiting for approval'|'Waiting for operator'|'Completed'|'Failed'|'Blocked'|'Cancelled';
export type Recipe={id:string;version:number;name:string;width:number;height:number;bleed:number;safe:number;minDpi:number;cutInstructions:string;created:string};
export type Task={id:string;title:string;status:Status;result:string;party:string;next:string;started?:string;finished?:string;updated:string;executions:string[];evidence:string[];error?:string;recovery?:string};
export type FileRecord={id:string;stage:'ORIGINAL'|'WORKING_COPY'|'PRINT_READY'|'PRODUCTION_OUTPUT';name:string;key:string;sha:string;bytes:number;created:string;parent?:string;method:string};
export type Inspection={pages:any[];errors:string[];warnings:string[];bleed:'correct'|'missing'|'unsuitable';engine:string;at:string};
export type Job={id:string;customer:string;quantity:number;sides:number;stock:string;finish:string;due:string;recipe:Recipe;tasks:Task[];files:FileRecord[];messages:{id:string;role:string;text:string;at:string}[];events:{id:string;text:string;at:string;actor:string}[];created:string;updated:string;revision:number;state:'active'|'paused'|'cancelled'|'complete';generation:number;inspection?:Inspection;verification?:any;bleedDecision?:string;approval?:{sha:string;fileId:string;actor:string;at:string;generation:number};authorization?:{sha:string;actor:string;at:string;generation:number};route?:any;settingsVersion?:number;qc?:any;approvalHistory?:any[];authorizationHistory?:any[]};
export const titles=['Capture order','Receive artwork','Check artwork','Decide bleed handling','Prepare artwork','Generate PRINT_READY','Verify PRINT_READY','Review and approve proof','Choose production route','Prepare imposition and RIP handoff','Verify shop readiness','Authorize production','Print','Cut and finish','Final quality check','Pack and complete'];
export const defaultRecipe:Recipe={id:'business-card',version:1,name:'Business card',width:3.5,height:2,bleed:0.125,safe:0.125,minDpi:300,cutInstructions:'Cut to 3.5 × 2 inches using the verified trim box. Check the first sheet for front/back alignment. Finish to the selected order specification; keep a reference sample.',created:new Date().toISOString()};
export function newTasks():Task[]{return titles.map((title,i)=>({id:`t${i+1}`,title,status:i===0?'Completed':'Pending',result:i===0?'Order details saved.':'Not started.',party:[0,1,7,8,9,11,12,13,14,15].includes(i)?'Operator':'Application',next:'',updated:new Date().toISOString(),executions:[],evidence:[]}));}
