import { z } from 'zod';
import {db,read,list,insert,now,hash,runtime,lock,unlock,save} from '@/lib/production/store';
import {user,passwordHash,session,cookie} from '@/lib/production/auth';
import {defaultRecipe,newTasks,type Job,type Recipe} from '@/lib/production/types';
import {event,task,latest,file,bytes,invalidate,requireBefore,queue,readiness,recover} from '@/lib/production/engine';
import {executionContext} from '@/lib/runtime';
import {converse} from '@/lib/production/ai';
import {providerOrder} from '@/lib/production/providers';
export const dynamic='force-dynamic';
const json=(value:any,status=200,headers:any={})=>Response.json(value,{status,headers:{'Cache-Control':'no-store',...headers}});
const orderSchema=z.object({customer:z.string().trim().min(1).max(180),quantity:z.number().int().min(1).max(1000000),sides:z.number().int().min(1).max(2),stock:z.string().min(1).max(100),finish:z.string().min(1).max(100),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).strict();
const settingsSchema=z.object({printer:z.string().max(120),stocks:z.array(z.string().min(1).max(100)).max(30),sides:z.array(z.number().int().min(1).max(2)).min(1),instructions:z.string().max(2000),model:z.string().max(100).optional()}).strict();
const recipeSchema=z.object({name:z.string().min(1).max(100),width:z.number().min(.5).max(20),height:z.number().min(.5).max(20),bleed:z.number().min(0).max(.5),safe:z.number().min(.05).max(.5),minDpi:z.number().int().min(72).max(1200),cutInstructions:z.string().min(1).max(2000)}).strict();
async function boundedForm(req:Request){const limit=4*1024*1024+65536;const declared=Number(req.headers.get('content-length')||0);if(declared>limit)throw new Error('Upload a PDF up to 4 MB.');const reader=req.body?.getReader();if(!reader)throw new Error('Upload a PDF file.');const chunks:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>limit){await reader.cancel();throw new Error('Upload a PDF up to 4 MB.');}chunks.push(part.value);}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.byteLength;}return new Request(req.url,{method:'POST',headers:req.headers,body:data}).formData();}
async function defaults(){let recipe=await read<Recipe>('recipe:business-card:1');if(!recipe){await db().prepare('INSERT OR IGNORE INTO records (id,kind,data) VALUES (?,?,?)').bind('recipe:business-card:1','recipe',JSON.stringify(defaultRecipe)).run();recipe=defaultRecipe;}return recipe;}
async function upsert(id:string,kind:string,data:any){await db().prepare('INSERT INTO records (id,kind,data) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,revision=records.revision+1').bind(id,kind,JSON.stringify(data)).run();}
async function route(req:Request){
 const path=new URL(req.url).pathname.slice(5).split('/').filter(Boolean),method=req.method;
 if(method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Request origin is not allowed.'},403);}
 if(path[0]==='auth'){
  const count=await db().prepare('SELECT COUNT(*) AS n FROM users').first<any>();
  if(method==='GET')return json({user:await user(req),needsSetup:count.n===0});
  const b:any=await req.json();if(path[1]==='logout'){const raw=req.headers.get('cookie')?.match(/p2g_session=([^;]+)/)?.[1];if(raw)await db().prepare('DELETE FROM sessions WHERE id=?').bind(await hash(raw)).run();return json({ok:true},200,{'Set-Cookie':'p2g_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'});}
  const data=z.object({email:z.string().email().max(200),password:z.string().min(12).max(200),name:z.string().min(1).max(80).optional()}).strict().parse(b);data.email=data.email.toLowerCase();
  const rateId=`auth-rate:${await hash(data.email)}:${Math.floor(Date.now()/900000)}`;const rate=await read(rateId);if((rate?.n||0)>=8)return json({error:'Too many sign-in attempts. Try again in 15 minutes.'},429);
  let u:any;if(path[1]==='setup'){if(count.n!==0)return json({error:'An administrator is already configured.'},409);u={id:'initial-admin',name:data.name||'Shop administrator',email:data.email,role:'admin'};await db().prepare('INSERT INTO users (id,email,name,role,password) VALUES (?,?,?,?,?)').bind(u.id,u.email,u.name,u.role,await passwordHash(data.password)).run();await defaults();}else{
   u=await db().prepare('SELECT * FROM users WHERE email=?').bind(data.email).first<any>();if(!u||await passwordHash(data.password,u.password.split(':')[0])!==u.password){await upsert(rateId,'rate',{n:(rate?.n||0)+1});return json({error:'Email or password is incorrect.'},401);}}
  const token=await session(u.id);return json({user:{id:u.id,name:u.name,email:u.email,role:u.role}},200,{'Set-Cookie':cookie(token,req)});
 }
 if(path[0]==='connector'){
  const secret=(runtime() as any).CONNECTOR_SECRET;if(!secret)return json({error:'Connector server secret has not been configured.'},503);
  const authorization=req.headers.get('authorization');if(!authorization||await hash(authorization)!==await hash(`Bearer ${secret}`))return json({error:'Connector authentication failed.'},401);
  if(method==='POST'){
   const b=z.object({timestamp:z.number(),nonce:z.string().uuid(),destination:z.string().min(1).max(500),writable:z.boolean(),capabilities:z.array(z.literal('pdf-hot-folder')),handoffs:z.array(z.object({jobId:z.string(),sha:z.string().length(64),generation:z.number().int(),fileId:z.string()})).max(30)}).strict().parse(await req.json());if(Math.abs(Date.now()-b.timestamp)>60000)return json({error:'Connector clock differs by more than one minute.'},409);
   await db().prepare('INSERT INTO nonces (id,created) VALUES (?,?)').bind(b.nonce,Date.now()).run();await db().prepare('DELETE FROM nonces WHERE created<?').bind(Date.now()-300000).run();await upsert('agent','agent',{lastSeen:now(),destination:b.destination,writable:b.writable,capabilities:b.capabilities});
   for(const ack of b.handoffs){const token=await lock(ack.jobId);try{const j=await read<Job>(ack.jobId);if(j&&j.state==='active'&&j.authorization?.sha===ack.sha&&j.authorization.generation===ack.generation&&j.generation===ack.generation&&latest(j,'PRINT_READY')?.id===ack.fileId&&!j.files.some(f=>f.stage==='PRODUCTION_OUTPUT'&&f.parent===ack.fileId)){const p=latest(j,'PRINT_READY')!;await file(j,'PRODUCTION_OUTPUT',await bytes(p),p,'Connector confirmed checksum after writing destination. This is file handoff, not proof of printing.');event(j,'Connector confirmed production file copied to destination. Printing still needs operator confirmation.');await save(j,token);}}finally{await unlock(ack.jobId,token);}}
   const currentSettings=await read('settings');const jobs=(await list<Job>('job')).filter(j=>j.state==='active'&&j.route?.settingsVersion===currentSettings?.version&&j.authorization?.generation===j.generation&&j.tasks[12].status!=='Completed').map(j=>({id:j.id,generation:j.generation,file:latest(j,'PRINT_READY'),authorized:j.authorization}));return json({jobs});
  }
  if(method==='GET'&&path[1]==='file'){const j=await read<Job>(path[2]);const f=j&&latest(j,'PRINT_READY');const settings=await read('settings');if(!j||!f||j.route?.settingsVersion!==settings?.version||j.state!=='active'||j.authorization?.sha!==f.sha||j.authorization.generation!==j.generation)return json({error:'This file is not authorized.'},403);return new Response(await bytes(f) as any,{headers:{'content-type':'application/pdf','Cache-Control':'no-store'}});}
  return json({error:'Connector operation not supported.'},404);
 }
 const u=await user(req);if(!u)return json({error:'Sign in to your shop.'},401);const admin=()=>{if(u.role!=='admin')throw new Error('Only an administrator can change shop configuration.');};
 if(path[0]==='users'){admin();if(method==='GET')return json((await db().prepare('SELECT id,email,name,role FROM users').all()).results);const b=z.object({email:z.string().email(),name:z.string().min(1).max(80),password:z.string().min(12).max(200),role:z.enum(['operator','admin'])}).strict().parse(await req.json());await db().prepare('INSERT INTO users (id,email,name,role,password) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),b.email.toLowerCase(),b.name,b.role,await passwordHash(b.password)).run();return json({ok:true});}
 if(path[0]==='recipes'){await defaults();if(method==='GET')return json((await list<Recipe>('recipe')).sort((a,b)=>b.version-a.version));admin();const b=recipeSchema.parse(await req.json());if(b.safe*2>=Math.min(b.width,b.height))throw new Error('Safe margin must fit within the finished size.');const token=await lock('recipe:business-card:1');try{const versions=await list<Recipe>('recipe');const version=Math.max(...versions.map(r=>r.version))+1;const r={...b,id:'business-card',version,created:now()};await insert(`recipe:business-card:${version}`,'recipe',r);return json(r);}finally{await unlock('recipe:business-card:1',token);}}
 if(path[0]==='settings'){const s=await read('settings')||{printer:'',stocks:['14pt matte','16pt soft touch'],sides:[1,2],instructions:'Operator-assisted Fiery/RIP handoff. No automatic printing.',model:'claude-sonnet-4-5',version:1};if(method==='GET'){const agent=await read('agent');const {model,...visible}=s;return json({...visible,aiConnected:providerOrder(runtime()).length>0,connectorConfigured:!!(runtime() as any).CONNECTOR_SECRET,agent,connected:!!agent?.lastSeen&&Date.now()-Date.parse(agent.lastSeen)<90000&&agent.writable});}admin();const b=settingsSchema.parse(await req.json());const changed=JSON.stringify([b.printer,b.stocks,b.sides,b.instructions])!==JSON.stringify([s.printer,s.stocks,s.sides,s.instructions]); const version=s.version+(changed?1:0);await upsert('settings','settings',{...b,version,updated:now()});if(changed){for(const job of await list<Job>('job')){if(!job.route||job.state!=='active'||job.tasks[12].status==='Completed')continue;const t=await lock(job.id).catch(()=>null);if(!t)continue;try{const current=await read<Job>(job.id) as Job;invalidate(current,8,'Shop production settings changed. Choose the route again; authorization revoked.');if(current.approval)current.approval.generation=current.generation;if(current.verification)current.verification.generation=current.generation;await save(current,t);}finally{await unlock(job.id,t);}}}return json({ok:true});}
 if(path[0]==='files'&&method==='GET'){const j=await read<Job>(path[1]),f=j?.files.find(f=>f.id===path[2]);if(!f)return json({error:'File not found.'},404);return new Response(await bytes(f) as any,{headers:{'Content-Type':'application/pdf','Content-Disposition':`${new URL(req.url).searchParams.has('download')?'attachment':'inline'}; filename="${f.stage}-${j!.id}.pdf"`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
 if(path[0]==='jobs'&&path.length===1){if(method==='GET'){const jobs=await list<Job>('job');return json(jobs.map(j=>({...j,messages:[],events:[]})));}const b=orderSchema.parse(await req.json());await defaults();const recipe=(await list<Recipe>('recipe')).sort((a,b)=>b.version-a.version)[0];const id=crypto.randomUUID(),j:Job={...b,id,recipe,tasks:newTasks(),files:[],messages:[],events:[],state:'active',created:now(),updated:now(),revision:0,generation:1};j.tasks[0].evidence=[`order:${id}`];task(j,1,'Waiting for operator','Upload a PDF containing the front and, for double-sided cards, the back.');event(j,'Order created.',u.name);await insert(id,'job',j);return json(j,201);}
 if(path[0]!=='jobs')return json({error:'Not found.'},404);
 let j=await read<Job>(path[1]);if(!j)return json({error:'Job not found.'},404);
 if(method==='GET'&&path[2]==='events'){let cancelled=false;const stream=new ReadableStream({start(controller){const encoder=new TextEncoder();const run=async()=>{let revision=-1;try{for(let n=0;n<15&&!cancelled;n++){const current=await recover(await read<Job>(j!.id) as Job),control=await read(`control:${j!.id}`);if(current.revision!==revision||n===0){revision=current.revision;controller.enqueue(encoder.encode(`id: ${revision}\ndata: ${JSON.stringify({...current,state:control?.state||current.state})}\n\n`));}else controller.enqueue(encoder.encode(': heartbeat\n\n'));await new Promise(resolve=>setTimeout(resolve,1000));}if(!cancelled)controller.close();}catch{if(!cancelled)controller.close();}};executionContext.getStore()?.waitUntil(run());},cancel(){cancelled=true;}});return new Response(stream,{headers:{'Content-Type':'text/event-stream','Cache-Control':'no-store','X-Accel-Buffering':'no'}});}
 if(method==='GET'){j=await recover(j);const c=await read(`control:${j.id}`);return json({...j,state:c?.state||j.state});}
 if(path[2]==='chat'){
  const b=z.object({message:z.string().trim().min(1).max(3000)}).strict().parse(await req.json());if(!providerOrder(runtime()).length)return json({error:'Print2Go Assistant needs server setup. Job buttons remain available.'},503);
  const stream=new TransformStream(),writer=stream.writable.getWriter(),encoder=new TextEncoder();const send=(type:string,data:any)=>{writer.write(encoder.encode(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`)).catch(()=>{});};const run=converse(j.id,b.message,u,send).catch(async()=>{send('error',{error:'The assistant or a tool could not finish. Review the saved task results and retry.'});const t=await lock(j!.id).catch(()=>null);if(t){try{const current=await read<Job>(j!.id);if(current){current.messages.push({id:crypto.randomUUID(),role:'system',text:'The assistant could not finish this message. Retry; no human approvals were granted.',at:now()});await save(current,t);}}finally{await unlock(j!.id,t);}}}).finally(()=>writer.close().catch(()=>{}));executionContext.getStore()?.waitUntil(run);return new Response(stream.readable,{headers:{'Content-Type':'text/event-stream','Cache-Control':'no-store','X-Accel-Buffering':'no'}});
 }
 if(path[2]==='control'){const b=z.object({state:z.enum(['active','paused','cancelled'])}).strict().parse(await req.json());if(j.state==='complete')throw new Error('Completed jobs cannot be paused or cancelled.');if(j.state==='cancelled')throw new Error('Cancelled jobs are closed.');await upsert(`control:${j.id}`,'control',{state:b.state,actor:u.name,at:now()});const t=await lock(j.id).catch(()=>null);if(t){try{j=await read<Job>(j.id) as Job;j.state=b.state;if(b.state==='cancelled')for(const task of j.tasks)if(task.status!=='Completed')task.status='Cancelled';event(j,`Job ${b.state==='active'?'resumed':b.state}.`,u.name);await save(j,t);}finally{await unlock(j.id,t);}}return json({ok:true});}
 if(path[2]==='process'){const b:any=await req.json();if(b.generation!==j.generation)throw new Error('Artwork version changed. Refresh before continuing.');const q=await queue(j.id,u);if(q.run){const ctx=executionContext.getStore();if(ctx)ctx.waitUntil(q.run());else await q.run();}return json({queued:!!q.run,execution:q.id},202);}
 const token=await lock(j.id);try{
 j=await read<Job>(j.id) as Job;const c=await read(`control:${j.id}`);if(c?.state)j.state=c.state;
 if(j.state!=='active')throw new Error(`This job is ${j.state}. Resume it before making changes.`);
 if(path[2]==='artwork'){
  if(j.tasks[12].status==='Completed')throw new Error('Printing has been confirmed. Create a new job for replacement artwork.');const data=await boundedForm(req),f=data.get('file');if(!(f instanceof File)||f.size>4*1024*1024||f.size<5)throw new Error('Upload a PDF up to 4 MB.');const b=new Uint8Array(await f.arrayBuffer());if(new TextDecoder().decode(b.slice(0,5))!=='%PDF-')throw new Error('This file is not a PDF.');const original=await file(j,'ORIGINAL',b,undefined,'Original upload preserved',f.name.slice(0,180));invalidate(j,2,'New artwork version: downstream checks and approvals invalidated.');j.inspection=undefined;task(j,1,'Completed','Original PDF saved. Ready to check artwork.',undefined,original.id);await save(j,token);return json(j);
 }
 const b:any=await req.json();if(b.generation!==j.generation)throw new Error('Job version changed. Refresh before continuing.');const ex=crypto.randomUUID();let action=String(b.action||''); const index=({bleed:3,approve:7,route:8,handoff:9,readiness:10,authorize:11,printed:12,cut:13,qc:14,pack:15} as Record<string,number>)[action]; if(index!==undefined&&j.tasks[index].status==='Completed')return json(j);
 if(action==='bleed'){requireBefore(j,3);if(j.inspection?.bleed!=='missing')throw new Error('A bleed decision is not required.');if(b.decision!=='blank-border')throw new Error('Choose the explicit blank-border option or upload corrected artwork.');j.bleedDecision='blank-border';j.tasks[3].party='Operator';task(j,3,'Completed',`Blank border outside trim explicitly accepted by ${u.name}. Content will not be stretched.`,ex,latest(j,'ORIGINAL')!.id);}
 else if(action==='approve'){requireBefore(j,7);const f=latest(j,'PRINT_READY');if(!f||b.sha!==f.sha||j.verification?.sha!==f.sha||j.verification?.generation!==j.generation||j.verification?.errors?.length)throw new Error('This proof is not the currently verified file.');if(b.acknowledged!==true)throw new Error('Confirm you reviewed all pages and inspection notes.');j.approval={sha:f.sha,fileId:f.id,actor:u.name,at:now(),generation:j.generation};(j.approvalHistory||=[]).push({...j.approval,recipeVersion:j.recipe.version});task(j,7,'Completed',`Proof approved by ${u.name} for file ${f.sha.slice(0,12)}.`,ex,f.id);task(j,8,'Waiting for operator','Choose a compatible printer and confirm the production settings.');}
 else if(action==='route'){requireBefore(j,8);const s=await read('settings');if(!s?.printer||!s.stocks.includes(j.stock)||!s.sides.includes(j.sides))throw new Error('No compatible printer route. Configure this stock and side count in Shop settings.');j.route={printer:s.printer,stock:j.stock,sides:j.sides,finish:j.finish,instructions:s.instructions,settingsVersion:s.version,at:now(),actor:u.name};j.settingsVersion=s.version;task(j,8,'Completed',`${s.printer} selected with ${j.stock}, ${j.sides} side(s), ${j.finish}.`,ex);task(j,9,'Waiting for operator','Download PRINT_READY. Prepare imposition in your RIP and confirm the file was staged without printing.');}
 else if(action==='handoff'){requireBefore(j,9);if(typeof b.note!=='string'||b.note.trim().length<5||b.note.length>1000)throw new Error('Record the actual RIP job name and imposition settings.');task(j,9,'Completed',`Operator-assisted RIP staging confirmed by ${u.name}: ${b.note.trim()}. No automated Fiery submission is claimed.`,ex,latest(j,'PRINT_READY')!.id);}
 else if(action==='readiness'){requireBefore(j,10);try{const evidence=await readiness(j);task(j,10,'Completed',`Connector reachable; destination writable: ${evidence.destination}.`,ex);j.tasks[10].evidence.push(JSON.stringify(evidence));task(j,11,'Waiting for approval','Authorize printing for this exact approved job version.');}catch(e){task(j,10,'Blocked',e instanceof Error?e.message:'Shop unavailable',ex);j.tasks[10].recovery='Connect the shop or update the route, then retry readiness.';await db().prepare('INSERT INTO executions (id,job_id,action,status,data,created) VALUES (?,?,?,?,?,?)').bind(ex,j.id,action,'Blocked',JSON.stringify({actor:u.name,generation:j.generation}),now()).run();await save(j,token);return json(j);}}
 else if(action==='authorize'){requireBefore(j,11);await readiness(j);const f=latest(j,'PRINT_READY');if(!f||b.sha!==f.sha||j.approval?.sha!==f.sha||j.approval.generation!==j.generation||b.acknowledged!==true)throw new Error('Human authorization must match the approved file version.');j.authorization={sha:f.sha,actor:u.name,at:now(),generation:j.generation};(j.authorizationHistory||=[]).push({...j.authorization,route:j.route});task(j,11,'Completed',`Production authorized by ${u.name} for ${f.sha.slice(0,12)}.`,ex,f.id);task(j,12,'Waiting for operator','Print using the configured RIP. Confirm only after the sheets are actually printed.');}
 else if(['printed','cut','qc','pack'].includes(action)){const i={printed:12,cut:13,qc:14,pack:15}[action] as number;requireBefore(j,i);const f=latest(j,'PRINT_READY');if(!f||b.sha!==f.sha||j.authorization?.sha!==f.sha||j.authorization.generation!==j.generation)throw new Error('Production authorization is invalid for this job version.');if(i===12){const settings=await read('settings');if(settings?.version!==j.route?.settingsVersion)throw new Error('Production settings changed. Choose the route again before printing.');}if(b.acknowledged!==true)throw new Error('Operator confirmation is required.');if(action==='qc'){const q=z.object({quantity:z.boolean(),alignment:z.boolean(),appearance:z.boolean(),finishing:z.boolean(),note:z.string().max(1000)}).strict().parse(b.checks);j.qc={...q,actor:u.name,at:now()};if(!q.quantity||!q.alignment||!q.appearance||!q.finishing){task(j,14,'Needs attention',`Quality check rejected by ${u.name}: ${q.note||'One or more checks failed'}.`,ex);j.authorization=undefined;task(j,15,'Blocked','Rework and a new production authorization are required.');await db().prepare('INSERT INTO executions (id,job_id,action,status,data,created) VALUES (?,?,?,?,?,?)').bind(ex,j.id,action,'Needs attention',JSON.stringify({actor:u.name,generation:j.generation}),now()).run();await save(j,token);return json(j);}}
 if(action==='pack'&&!['collection','delivery'].includes(b.method))throw new Error('Choose collection or delivery readiness.');task(j,i,'Completed',`${action==='printed'?'Physical printing':action==='cut'?'Cutting and finishing':action==='qc'?'Quantity, alignment, appearance and finishing':b.method==='delivery'?'Packed and ready for delivery':'Packed and ready for collection'} confirmed by ${u.name}.`,ex,f.id);if(i<15)task(j,i+1,'Waiting for operator',i===12?j.recipe.cutInstructions:i===13?'Check quantity, alignment, appearance and finishing.':'Pack the finished order and record collection or delivery readiness.');else{j.state='complete';await upsert(`control:${j.id}`,'control',{state:'complete'});}}
 else if(action==='rework'){if(j.tasks[14].status!=='Needs attention')throw new Error('Rework is available after a rejected quality check.');for(let i=11;i<16;i++){j.tasks[i].status='Pending';j.tasks[i].result='Rework requires new physical confirmations.';j.tasks[i].finished=undefined;}j.authorization=undefined;task(j,11,'Waiting for approval','Rework: authorize production again for the approved file.');}
 else if(action==='reroute'){if(j.tasks[12].status==='Completed')throw new Error('Cannot change route after printing.');invalidate(j,8,'Production route reset. New route and authorization required.');if(j.approval)j.approval.generation=j.generation;if(j.verification)j.verification.generation=j.generation;}
 else throw new Error('Unsupported action.');
 await db().prepare('INSERT INTO executions (id,job_id,action,status,data,created) VALUES (?,?,?,?,?,?)').bind(ex,j.id,action,'Completed',JSON.stringify({actor:u.name,generation:j.generation}),now()).run();await save(j,token);return json(j);
 }finally{await unlock(j.id,token);}
}
export async function GET(req:Request){try{return await route(req);}catch(e){return json({error:e instanceof Error?e.message:'Unable to load saved data. Retry.'},503);}}
export async function POST(req:Request){try{return await route(req);}catch(e){if(e instanceof z.ZodError)return json({error:e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')},400);return json({error:e instanceof Error?e.message:'Unable to complete the action. Retry.'},409);}}
